name: Generate Snake Animation

on:
  # Roda a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
 
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#339A3E&color_dots=#17381A,#206024,#339A3E,#47c44d&color_bg=#ffffff
            dist/github-contribution-grid-snake-dark.svg?color_snake=#339A3E&color_dots=#17381A,#206024,#339A3E,#47c44d&color_bg=#0d1117
