name: Generate Snake Animation

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          outputs: |
            # Arquivo para tema escuro, enviado para o branch 'output'
            github-contribution-grid-snake-dark.svg@output?color_snake=#339A3E&color_dots=#17381A,#206024,#339A3E,#47c44d&color_bg=#0d1117

            # Arquivo para tema claro, enviado para o branch 'output'
            github-contribution-grid-snake.svg@output?color_snake=#339A3E&color_dots=#17381A,#206024,#339A3E,#47c44d&color_bg=#ffffff
